// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDo7k7ZeQpzw-FKBuY4Aebo3_HTYNkAoo',
    appId: '1:1098373753872:web:0816c581f41923ecac2e95',
    messagingSenderId: '1098373753872',
    projectId: 'health-tracking-system-700bf',
    authDomain: 'health-tracking-system-700bf.firebaseapp.com',
    storageBucket: 'health-tracking-system-700bf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJi50qFPLpioWrRsLydiCmYzxNxbd_8T0',
    appId: '1:1098373753872:android:3927a1d586a82e08ac2e95',
    messagingSenderId: '1098373753872',
    projectId: 'health-tracking-system-700bf',
    storageBucket: 'health-tracking-system-700bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRzgfu1ZRwbpTnJaKRbgFi3Q1geXGapVM',
    appId: '1:1098373753872:ios:56d02d083650d500ac2e95',
    messagingSenderId: '1098373753872',
    projectId: 'health-tracking-system-700bf',
    storageBucket: 'health-tracking-system-700bf.firebasestorage.app',
    iosBundleId: 'com.example.healthCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRzgfu1ZRwbpTnJaKRbgFi3Q1geXGapVM',
    appId: '1:1098373753872:ios:56d02d083650d500ac2e95',
    messagingSenderId: '1098373753872',
    projectId: 'health-tracking-system-700bf',
    storageBucket: 'health-tracking-system-700bf.firebasestorage.app',
    iosBundleId: 'com.example.healthCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDo7k7ZeQpzw-FKBuY4Aebo3_HTYNkAoo',
    appId: '1:1098373753872:web:b0ac372863be05c5ac2e95',
    messagingSenderId: '1098373753872',
    projectId: 'health-tracking-system-700bf',
    authDomain: 'health-tracking-system-700bf.firebaseapp.com',
    storageBucket: 'health-tracking-system-700bf.firebasestorage.app',
  );
}
